import { Court } from '@/types/courts';
import { Event } from '@/types/event';
import { User } from '@/types/user';
import { Club } from '@/types/club';

export const mockUser: User = {
  id: '1',
  email: 'john.doe@example.com',
  name: 'John Doe',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
  createdAt: new Date().toISOString(),
  over18: true,
  clubs: [],
  courtHistory: [],
  badges: [],
};

export const mockCourts: Court[] = [
  {
    id: '1',
    name: 'Cubbon Park',
    description: 'A vast, lush urban park in the heart of Bangalore — ideal for outdoor meetups, morning yoga, photography walks, and casual picnics.',
    location: {
      latitude: 12.9763,
      longitude: 77.5929,
      geohash: '',
      address: 'Kasturba Road, Sampangi Rama Nagar, Bengaluru, Karnataka 560001',
    },
    images: [
      'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1005417/pexels-photo-1005417.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    tags: ['Outdoor', 'Free', 'Pet Friendly', 'Wheelchair Accessible', 'Metro Accessible'],
    checkedInUsers: ['1', '2'],
    followers: ['1', '2', '3'],
    createdBy: '1',
    createdAt: new Date().toISOString(),
    rating: 4.7,
    reviews: [],
    openingHours: {
      alwaysOpen: true,
      monday: { alwaysOpen: true, openTime: '', closeTime: '' },
      tuesday: { alwaysOpen: true, openTime: '', closeTime: '' },
      wednesday: { alwaysOpen: true, openTime: '', closeTime: '' },
      thursday: { alwaysOpen: true, openTime: '', closeTime: '' },
      friday: { alwaysOpen: true, openTime: '', closeTime: '' },
      saturday: { alwaysOpen: true, openTime: '', closeTime: '' },
      sunday: { alwaysOpen: true, openTime: '', closeTime: '' },
    },
    verified: true,
  },
  {
    id: '2',
    name: 'Koramangala Social Hub',
    description: 'A vibrant co-working and community space in Koramangala, perfect for tech meetups, workshops, and networking events.',
    location: {
      latitude: 12.9352,
      longitude: 77.6245,
      geohash: '',
      address: '5th Block, Koramangala, Bengaluru, Karnataka 560095',
    },
    images: [
      'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    tags: ['Indoor', 'Café Nearby', 'Metro Accessible', 'Seating', 'Lighting'],
    checkedInUsers: ['3'],
    followers: ['1', '4'],
    createdBy: '2',
    createdAt: new Date().toISOString(),
    rating: 4.4,
    reviews: [],
    openingHours: {
      alwaysOpen: false,
      monday: { alwaysOpen: false, openTime: '09:00', closeTime: '21:00' },
      tuesday: { alwaysOpen: false, openTime: '09:00', closeTime: '21:00' },
      wednesday: { alwaysOpen: false, openTime: '09:00', closeTime: '21:00' },
      thursday: { alwaysOpen: false, openTime: '09:00', closeTime: '21:00' },
      friday: { alwaysOpen: false, openTime: '09:00', closeTime: '22:00' },
      saturday: { alwaysOpen: false, openTime: '10:00', closeTime: '22:00' },
      sunday: { alwaysOpen: false, openTime: '10:00', closeTime: '20:00' },
    },
    verified: false,
  },
];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Sunset Photography Walk',
    description: 'Join fellow photography enthusiasts for a golden-hour walk through Cubbon Park. All skill levels welcome!',
    courtId: '1',
    mainOrganiser: { type: 'user', id: '1' },
    organiserUserIds: ['1'],
    organiserClubIds: [],
    startDate: new Date(Date.now() + 86400000).toISOString(),
    endDate: new Date(Date.now() + 86400000 + 7200000).toISOString(),
    maxParticipants: 15,
    currentParticipants: 8,
    pricing: [],
    ticketDeadline: 'upcoming',
    isPrivate: false,
    participants: [],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    acceptingParticipants: true,
    verifyParticipants: false,
  },
  {
    id: '2',
    title: 'Language Exchange Meetup',
    description: 'Practice a new language and meet people from all over the world. Casual, conversational, and completely free!',
    courtId: '2',
    mainOrganiser: { type: 'user', id: '2' },
    organiserUserIds: ['2'],
    organiserClubIds: [],
    startDate: new Date(Date.now() + 259200000).toISOString(),
    endDate: new Date(Date.now() + 259200000 + 7200000).toISOString(),
    maxParticipants: 20,
    currentParticipants: 11,
    pricing: [],
    ticketDeadline: 'upcoming',
    isPrivate: false,
    participants: [],
    status: 'upcoming',
    createdAt: new Date().toISOString(),
    acceptingParticipants: true,
    verifyParticipants: false,
  },
];

export const mockClubs: Club[] = [
  {
    id: '1',
    name: 'Bangalore Explorers',
    description: 'A thriving community for newcomers and locals alike in Bangalore. We organise hiking trips, cultural events, and casual meetups to help you connect with the city.',
    logo: 'https://images.pexels.com/photos/1005417/pexels-photo-1005417.jpeg?auto=compress&cs=tinysrgb&w=400',
    adminId: '1',
    members: ['1', '2', '3', '4', '5'],
    trainingSchedule: [
      {
        id: '1',
        title: 'Saturday Hike',
        courtId: '1',
        startTime: new Date(Date.now() + 86400000),
        endTime: new Date(Date.now() + 86400000 + 14400000),
        maxParticipants: 20,
        currentParticipants: 12,
        price: 0,
        recurringDays: ['Saturday'],
      },
    ],
    courtIds: ['1'],
    fees: {
      monthly: 0,
      session: 0,
    },
    createdAt: new Date(),
  },
];