export interface UKUniversity {
  id: string;
  name: string;
}

export const UK_UNIVERSITIES: UKUniversity[] = [
  { id: 'oxford', name: 'University of Oxford' },
  { id: 'cambridge', name: 'University of Cambridge' },
  { id: 'imperial', name: 'Imperial College London' },
  { id: 'ucl', name: 'University College London' },
  { id: 'lse', name: 'London School of Economics and Political Science' },
  { id: 'edinburgh', name: 'University of Edinburgh' },
  { id: 'manchester', name: 'University of Manchester' },
  { id: 'kcl', name: "King's College London" },
  { id: 'bristol', name: 'University of Bristol' },
  { id: 'warwick', name: 'University of Warwick' },
  { id: 'leeds', name: 'University of Leeds' },
  { id: 'birmingham', name: 'University of Birmingham' },
  { id: 'nottingham', name: 'University of Nottingham' },
  { id: 'southampton', name: 'University of Southampton' },
  { id: 'sheffield', name: 'University of Sheffield' },
  { id: 'york', name: 'University of York' },
  { id: 'durham', name: 'Durham University' },
  { id: 'exeter', name: 'University of Exeter' },
  { id: 'lancaster', name: 'Lancaster University' },
  { id: 'loughborough', name: 'Loughborough University' },
  { id: 'bath', name: 'University of Bath' },
  { id: 'leicester', name: 'University of Leicester' },
  { id: 'reading', name: 'University of Reading' },
  { id: 'surrey', name: 'University of Surrey' },
  { id: 'sussex', name: 'University of Sussex' },
  { id: 'queen-mary', name: "Queen Mary University of London" },
  { id: 'newcastle', name: 'Newcastle University' },
  { id: 'cardiff', name: 'Cardiff University' },
  { id: 'glasgow', name: 'University of Glasgow' },
  { id: 'aberdeen', name: 'University of Aberdeen' },
  { id: 'st-andrews', name: 'University of St Andrews' },
  { id: 'strathclyde', name: 'University of Strathclyde' },
  { id: 'heriot-watt', name: 'Heriot-Watt University' },
  { id: 'dundee', name: 'University of Dundee' },
  { id: 'swansea', name: 'Swansea University' },
  { id: 'bangor', name: 'Bangor University' },
  { id: 'aberystwyth', name: 'Aberystwyth University' },
  { id: 'liverpool', name: 'University of Liverpool' },
  { id: 'east-anglia', name: 'University of East Anglia' },
  { id: 'essex', name: 'University of Essex' },
  { id: 'kent', name: 'University of Kent' },
  { id: 'royal-holloway', name: 'Royal Holloway, University of London' },
  { id: 'soas', name: 'SOAS University of London' },
  { id: 'city', name: 'City, University of London' },
  { id: 'brunel', name: 'Brunel University London' },
  { id: 'golden-smiths', name: 'Goldsmiths, University of London' },
  { id: 'roehampton', name: 'University of Roehampton' },
  { id: 'westminster', name: 'University of Westminster' },
  { id: 'greenwich', name: 'University of Greenwich' },
  { id: 'metropolitan', name: 'London Metropolitan University' },
  { id: 'south-bank', name: 'London South Bank University' },
  { id: 'kingston', name: 'Kingston University' },
  { id: 'middlesex', name: 'Middlesex University' },
  { id: 'east-london', name: 'University of East London' },
  { id: 'birkbeck', name: 'Birkbeck, University of London' },
  { id: 'stirling', name: 'University of Stirling' },
  { id: 'huddersfield', name: 'University of Huddersfield' },
  { id: 'portsmouth', name: 'University of Portsmouth' },
  { id: 'plymouth', name: 'University of Plymouth' },
  { id: 'bournemouth', name: 'Bournemouth University' },
  { id: 'brighton', name: 'University of Brighton' },
  { id: 'oxford-brookes', name: 'Oxford Brookes University' },
  { id: 'coventry', name: 'Coventry University' },
  { id: 'derby', name: 'University of Derby' },
  { id: 'nottingham-trent', name: 'Nottingham Trent University' },
  { id: 'leeds-beckett', name: 'Leeds Beckett University' },
  { id: 'manchester-met', name: 'Manchester Metropolitan University' },
  { id: 'salford', name: 'University of Salford' },
  { id: 'bolton', name: 'University of Bolton' },
  { id: 'central-lancashire', name: 'University of Central Lancashire' },
  { id: 'cumbria', name: 'University of Cumbria' },
  { id: 'edge-hill', name: 'Edge Hill University' },
  { id: 'liverpool-john-moores', name: 'Liverpool John Moores University' },
  { id: 'liverpool-hope', name: 'Liverpool Hope University' },
  { id: 'chester', name: 'University of Chester' },
  { id: 'glyndwr', name: 'Wrexham Glyndŵr University' },
];
